(()=>{
let detected='dynasty';let override=localStorage.getItem('dmLeagueMode')||'auto';const mode=()=>override==='auto'?detected:override;
function ageNow(p){const a=+(p.age||26);if(p.position==='RB')return a<=26?5:a<=28?2:a<=30?-2:-6;if(p.position==='WR')return a<=29?4:a<=31?1:-4;if(p.position==='TE')return a<=30?3:-2;if(p.position==='QB')return a<=34?2:-2;return 0}
function seasonRank(p){const d=window.DMREDRAFT,a=+(d?.adp?.[p.player_id]);if(Number.isFinite(a)&&a>0)return a;const s=+p.search_rank;return Number.isFinite(s)&&s>0&&s<1000?s:marketRank(p)}
function liveBoost(p){const d=window.DMREDRAFT,pr=+(d?.proj?.[p.player_id]),vg=+(d?.vegas?.[p.player_id]?.score||0);return (Number.isFinite(pr)?Math.min(30,pr*.12):0)+(Number.isFinite(vg)?vg:0)}
function paint(){const l=document.getElementById('dmModeLabel'),n=document.getElementById('dmModeNote');if(l)l.textContent='LEAGUE MODE: '+mode().toUpperCase()+(override==='auto'?' • AUTO':' • MANUAL');if(n)n.textContent=mode()==='dynasty'?'Long-term value, age curve and roster construction are emphasized.':'Current-season role, lineup value and positional scarcity are emphasized; dynasty age premiums are reduced.';}
async function detect(){const id=document.getElementById('leagueId')?.value.trim();if(!id)return;try{const r=await fetch('https://api.sleeper.app/v1/league/'+id);if(!r.ok)return;const L=await r.json();const t=Number(L?.settings?.type);if(t===2)detected='dynasty';else if(t===0)detected='redraft';else if(/dynasty/i.test(L?.name||''))detected='dynasty';else detected='redraft';paint();if(typeof render==='function')render();}catch(e){console.warn('Mode detection skipped',e)}}
const profile=document.getElementById('profile');if(profile&&!document.getElementById('dmModeSelect')){profile.insertAdjacentHTML('afterend','<div class="call" style="margin-top:10px"><b id="dmModeLabel">LEAGUE MODE: DYNASTY</b><div class="small" id="dmModeNote" style="margin-top:4px">Auto-detects from Sleeper.</div><select id="dmModeSelect" style="margin-top:7px"><option value="auto">Auto Detect</option><option value="dynasty">Force Dynasty</option><option value="redraft">Force Redraft</option></select></div>');const s=document.getElementById('dmModeSelect');s.value=override;s.onchange=()=>{override=s.value;localStorage.setItem('dmLeagueMode',override);paint();if(typeof render==='function')render()}}
if(typeof ftScore==='function'&&typeof ranked==='function'){const dynastyScore=ftScore,dynastyRanked=ranked;const redraftScore=p=>120-seasonRank(p)*.72+ageNow(p)+fit(p)+liveBoost(p);ftScore=function(p){return mode()==='dynasty'?dynastyScore(p):redraftScore(p)};ranked=function(){if(mode()==='dynasty')return dynastyRanked();const a=avail(),s=[...a].sort((x,y)=>redraftScore(y)-redraftScore(x)||seasonRank(x)-seasonRank(y)),m=[...a].sort((x,y)=>marketRank(x)-marketRank(y)),sr=new Map(),mr=new Map();s.forEach((p,i)=>sr.set(p.player_id,i+1));m.forEach((p,i)=>mr.set(p.player_id,i+1));return a.map(p=>{const rr=sr.get(p.player_id),mm=mr.get(p.player_id);return{p,m:mm,f:rr,blend:.95*rr+.05*mm,gap:mm-rr}}).sort((a,b)=>a.blend-b.blend||a.f-b.f)}}
const b=document.getElementById('load');if(b)b.addEventListener('click',()=>setTimeout(detect,250));paint();detect();
})();