const CACHE='full-throttle-v9';
const ASSETS=['./manifest.webmanifest','./icon-192.png','./icon-512.png'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)));self.skipWaiting();});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))));self.clients.claim();});
function patchHtml(text){
  const polish=`
<style id="ft-public-polish">
:root{--surface:#0a1d12;--surface2:#0d2617;--gold:#f2c94c;--soft:#b7c6b9}
body{background-attachment:fixed}
header{position:sticky;top:0;z-index:40;box-shadow:0 8px 28px rgba(0,0,0,.28)}
header .wrap{display:flex;align-items:center;justify-content:space-between;gap:16px}
header h1{letter-spacing:.025em}.sub{letter-spacing:.055em}
.card{box-shadow:0 12px 28px rgba(0,0,0,.18);backdrop-filter:blur(4px)}
.card h2{margin-top:2px}.call{border-color:#3a6547}.player{transition:background .15s ease}.player:hover{background:rgba(28,74,45,.42)}
button{transition:transform .12s ease,filter .12s ease}button:hover{filter:brightness(1.05)}button:active{transform:translateY(1px)}
.sitebar{max-width:1400px;margin:0 auto;padding:9px 14px 0;display:flex;gap:8px;flex-wrap:wrap;align-items:center}.sitechip{font-size:11px;color:var(--soft);border:1px solid #31553b;background:#081a10;border-radius:999px;padding:5px 9px}.sitechip strong{color:var(--gold)}
.appnav{max-width:1400px;margin:10px auto 0;padding:0 14px;display:flex;gap:7px;overflow-x:auto;scrollbar-width:none}.appnav::-webkit-scrollbar{display:none}.apptab{width:auto;min-width:max-content;padding:9px 13px;min-height:38px;border:1px solid #31553b;background:#0a1d12;color:#d9e4da;border-radius:10px;text-transform:none;font-size:12px}.apptab.active{background:var(--gold);color:#172014;border-color:var(--gold)}
.app-pane{max-width:1400px;margin:14px auto;padding:0 14px}.app-pane.hidden{display:none}.tool-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:14px}.tool-card{background:linear-gradient(145deg,#102719fa,#08170efa);border:1px solid #31553b;border-radius:14px;padding:15px;box-shadow:0 12px 28px rgba(0,0,0,.18)}.tool-card h2,.tool-card h3{margin-top:0;text-transform:uppercase;letter-spacing:.07em}.tool-card h2{font-size:15px}.tool-card h3{font-size:12px;color:#a9b8aa}.roster-list{display:grid;gap:7px}.roster-player{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:10px;border:1px solid #2f5239;border-radius:10px;background:#07170e}.roster-player strong{display:block}.roster-meta{font-size:11px;color:#a9b8aa;margin-top:3px}.asset-tag{font-size:10px;font-weight:800;border-radius:999px;padding:5px 8px;border:1px solid #3a6547;white-space:nowrap}.asset-core{color:#f2c94c}.asset-hold{color:#a9d6b1}.asset-review{color:#e4b98a}.placeholder-card{min-height:280px;display:flex;align-items:center;justify-content:center;text-align:center}.placeholder-card .inner{max-width:530px}.placeholder-card .icon{font-size:38px;margin-bottom:8px}.placeholder-card p{color:#a9b8aa;line-height:1.6}.guardrail{padding:10px;border-radius:10px;border:1px solid #416e4d;background:#0b2114;font-size:11px;color:#c6d5c8;line-height:1.5}.guardrail b{color:#f2c94c}
.adrail{position:fixed;top:168px;width:145px;min-height:460px;border:1px dashed #45634c;border-radius:12px;background:rgba(7,23,14,.75);display:flex;align-items:center;justify-content:center;text-align:center;color:#829487;font-size:11px;line-height:1.45;padding:14px;z-index:5}.adrail.left{left:12px}.adrail.right{right:12px}.adrail b{display:block;color:#b6c4b8;margin-bottom:5px}.adrail span{opacity:.78}
.public-info{max-width:1400px;margin:18px auto 42px;padding:0 14px}.info-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;align-items:start}.info-box{background:#081a10;border:1px solid #31553b;border-radius:12px;padding:13px;align-self:start}.info-box summary{cursor:pointer;font-weight:800;text-transform:uppercase;letter-spacing:.06em;font-size:12px;color:#e9eee9}.info-box p{font-size:11px;line-height:1.55;color:#aebcaf;margin:10px 0 0}.legal{font-size:10px;color:#809085;text-align:center;margin-top:14px;line-height:1.5}.mobile-ad{display:none;margin:12px 10px 0;border:1px dashed #45634c;border-radius:10px;text-align:center;color:#829487;font-size:10px;padding:9px}
@media(max-width:1710px){.adrail{display:none}}
@media(max-width:1000px){header{position:static}.info-grid{grid-template-columns:1fr 1fr}.sitebar{padding-top:7px}.mobile-ad{display:block}.tool-grid{grid-template-columns:1fr}}
@media(max-width:650px){header .wrap{display:block}.sitebar{gap:5px}.sitechip{font-size:10px;padding:4px 7px}.info-grid{grid-template-columns:1fr}.public-info{margin-top:10px}.card,.tool-card{box-shadow:none}.appnav{position:sticky;top:0;z-index:35;background:#06120bf5;padding-top:8px;padding-bottom:8px;margin-top:7px}.apptab{font-size:11px;padding:8px 10px}.roster-player{grid-template-columns:1fr}}
</style>`;
  const sitebar=`<div class="sitebar"><span class="sitechip"><strong>FULL THROTTLE</strong> Fantasy Football Intelligence</span><span class="sitechip">Sleeper League Adaptive</span><span class="sitechip">Dynasty + Weekly Tools</span></div><div class="mobile-ad">AD SPACE • reserved for a future sponsor or ad network</div>`;
  const nav=`<nav class="appnav" id="ftNav"><button class="apptab active" data-pane="draft">🏈 Draft Lab</button><button class="apptab" data-pane="team">🏠 My Team</button><button class="apptab" data-pane="lineup">📋 Lineup</button><button class="apptab" data-pane="waivers">🔄 Waivers</button><button class="apptab" data-pane="trades">🤝 Trades</button><button class="apptab" data-pane="players">📈 Players</button></nav>`;
  const manager=`
<section id="teamPane" class="app-pane hidden"><div class="tool-grid"><div class="tool-card"><h2>🏠 My Team</h2><div class="guardrail"><b>Roster-value protection:</b> weekly matchup, injury or bye-week availability will never by itself make a dynasty asset droppable. Drop decisions will use long-term value separately from weekly lineup value.</div><label style="margin-top:12px">Select your Sleeper roster</label><select id="ftRosterSelect"><option value="">Load your league in Draft Lab first</option></select><button id="ftLoadRoster" style="margin-top:8px">Load My Team</button><div id="ftTeamStatus" class="small" style="margin-top:8px"></div><h3 style="margin-top:16px">Roster</h3><div id="ftRosterList" class="roster-list"></div></div><div class="tool-card"><h2>Roster Command</h2><div id="ftRosterSummary" class="call">Load a league and choose your roster to see dynasty-oriented roster status.</div><h3 style="margin-top:16px">Status meanings</h3><div class="roster-list"><div class="roster-player"><div><strong>🔒 Core Asset</strong><div class="roster-meta">High-value dynasty cornerstone. Do not drop for a one-week issue.</div></div></div><div class="roster-player"><div><strong>✅ Strong Hold</strong><div class="roster-meta">Meaningful roster asset; waiver decisions should compare long-term value first.</div></div></div><div class="roster-player"><div><strong>🟡 Hold / Monitor</strong><div class="roster-meta">Depth asset. Role, trend and available replacements matter.</div></div></div><div class="roster-player"><div><strong>🔎 Review</strong><div class="roster-meta">Bottom-roster candidate to compare against waivers; not an automatic drop.</div></div></div></div></div></div></section>
<section id="lineupPane" class="app-pane hidden"><div class="tool-card placeholder-card"><div class="inner"><div class="icon">📋</div><h2>Lineup Optimizer</h2><p>This tab is next: weekly start/sit recommendations using your scoring, opponent, player usage, injuries, bye weeks, matchup data and Vegas expectations while keeping weekly value separate from dynasty value.</p></div></div></section>
<section id="waiversPane" class="app-pane hidden"><div class="tool-card placeholder-card"><div class="inner"><div class="icon">🔄</div><h2>Waiver Assistant</h2><p>This will compare available players directly with the bottom of your roster and recommend <b>who to add and exactly who is safe to drop</b>. Bye weeks alone will never trigger a drop recommendation.</p></div></div></section>
<section id="tradesPane" class="app-pane hidden"><div class="tool-card placeholder-card"><div class="inner"><div class="icon">🤝</div><h2>Trade Center</h2><p>This will evaluate dynasty value, lineup impact, age curve, roster construction and contender/rebuild direction rather than relying on a single trade-calculator number.</p></div></div></section>
<section id="playersPane" class="app-pane hidden"><div class="tool-card placeholder-card"><div class="inner"><div class="icon">📈</div><h2>Player Intelligence</h2><p>This will become the weekly player research hub for dynasty value, rest-of-season outlook, Vegas signal, historical profile, usage trends and roster fit.</p></div></div></section>`;
  const ads=`<aside class="adrail left"><div><b>AD SPACE</b><span>Reserved for a future sponsor or ad network.</span></div></aside><aside class="adrail right"><div><b>AD SPACE</b><span>Reserved for a future sponsor or ad network.</span></div></aside>`;
  const footer=`<section class="public-info"><div class="info-grid"><details class="info-box"><summary>About</summary><p>Full Throttle is an independent fantasy-football assistant built to help dynasty managers handle drafts, roster decisions and weekly team management.</p></details><details class="info-box"><summary>How It Works</summary><p>Load a Sleeper league once, then move between Draft Lab and team-management tools. Draft rankings blend dynasty startup market value with league-specific Full Throttle adjustments.</p></details><details class="info-box"><summary>Privacy</summary><p>The app uses the public Sleeper API to read league and draft information you request. Lightweight preferences may be stored locally in your browser. Full Throttle does not require a Sleeper password.</p></details><details class="info-box"><summary>Disclaimer</summary><p>Rankings and recommendations are informational fantasy-football analysis, not guarantees of player performance or financial outcomes. Full Throttle is not affiliated with Sleeper or the NFL.</p></details></div><div class="legal">© Full Throttle Draft Lab • Independent fantasy-football tool • Player, team and league names belong to their respective owners.</div></section>`;
  const appjs=`<script id="ft-manager-tabs">
(function(){
 const paneIds={draft:'draftPane',team:'teamPane',lineup:'lineupPane',waivers:'waiversPane',trades:'tradesPane',players:'playersPane'};
 function showPane(key){Object.entries(paneIds).forEach(([k,id])=>{const el=document.getElementById(id);if(el)el.classList.toggle('hidden',k!==key);});document.querySelectorAll('.apptab').forEach(b=>b.classList.toggle('active',b.dataset.pane===key));if(key==='team')refreshTeamChoices();window.scrollTo({top:0,behavior:'smooth'});}
 document.addEventListener('click',e=>{const b=e.target.closest('.apptab');if(b)showPane(b.dataset.pane);});
 document.addEventListener('toggle',function(e){if(e.target&&e.target.matches('.info-box')&&e.target.open){document.querySelectorAll('.info-box').forEach(box=>{if(box!==e.target)box.open=false;});}},true);
 function leagueId(){const el=document.getElementById('leagueId');return el?el.value.trim():'';}
 function rosterLabel(r,u){const meta=(u&&u.metadata)||{};return meta.team_name||u?.display_name||u?.username||('Roster '+r.roster_id);}
 async function refreshTeamChoices(){const sel=document.getElementById('ftRosterSelect'),status=document.getElementById('ftTeamStatus');if(!sel)return;const id=leagueId();if(!id){sel.innerHTML='<option value="">Load a league in Draft Lab first</option>';return;}try{status.textContent='Reading league rosters…';const [rr,ur]=await Promise.all([fetch('https://api.sleeper.app/v1/league/'+id+'/rosters'),fetch('https://api.sleeper.app/v1/league/'+id+'/users')]);if(!rr.ok)throw new Error('Could not read rosters');const rosters=await rr.json(),users=ur.ok?await ur.json():[];window.ftRosters=rosters;window.ftUsers=users;const um=new Map(users.map(u=>[u.user_id,u]));sel.innerHTML=rosters.map(r=>'<option value="'+r.roster_id+'">'+rosterLabel(r,um.get(r.owner_id))+'</option>').join('');if(typeof state!=='undefined'&&state.slot&&rosters.some(r=>r.roster_id===state.slot))sel.value=state.slot;status.textContent='Choose your team, then tap Load My Team.';}catch(err){status.textContent='Could not load rosters: '+err.message;}}
 function assetStatus(p){let mr=999;try{mr=typeof marketRank==='function'?marketRank(p):999}catch(e){}if(mr<=36)return['🔒 Core Asset','asset-core'];if(mr<=100)return['✅ Strong Hold','asset-hold'];if(mr<=180)return['🟡 Hold / Monitor','asset-hold'];return['🔎 Review','asset-review'];}
 async function loadMyTeam(){const id=leagueId(),rid=+document.getElementById('ftRosterSelect').value,status=document.getElementById('ftTeamStatus'),list=document.getElementById('ftRosterList'),summary=document.getElementById('ftRosterSummary');if(!id||!rid){status.textContent='Load your league and select a roster first.';return;}try{status.textContent='Loading your team…';let rosters=window.ftRosters;if(!Array.isArray(rosters)){const r=await fetch('https://api.sleeper.app/v1/league/'+id+'/rosters');rosters=await r.json();}const roster=rosters.find(x=>+x.roster_id===rid);if(!roster)throw new Error('Roster not found');if(typeof state!=='undefined'&&(!state.players||!state.players.length)){const pr=await fetch('https://api.sleeper.app/v1/players/nfl');const P=await pr.json();state.players=Object.values(P).filter(p=>p&&p.player_id&&['QB','RB','WR','TE'].includes(p.position)).map(p=>({...p,age:+p.age||26}));}const ids=[...(roster.players||[])];const reserve=new Set(roster.reserve||[]),taxi=new Set(roster.taxi||[]),starters=new Set(roster.starters||[]);const ps=ids.map(pid=>state.players.find(p=>p.player_id===pid)).filter(Boolean).sort((a,b)=>{const aa=starters.has(a.player_id)?0:taxi.has(a.player_id)?2:reserve.has(a.player_id)?3:1,bb=starters.has(b.player_id)?0:taxi.has(b.player_id)?2:reserve.has(b.player_id)?3:1;return aa-bb;});list.innerHTML=ps.map(p=>{const [tag,cls]=assetStatus(p);const bucket=starters.has(p.player_id)?'Starter':taxi.has(p.player_id)?'Taxi':reserve.has(p.player_id)?'IR / Reserve':'Bench';return '<div class="roster-player"><div><strong>'+name(p)+'</strong><div class="roster-meta">'+(p.team||'FA')+' • '+p.position+' • '+bucket+' • Age '+(p.age||'—')+'</div></div><span class="asset-tag '+cls+'">'+tag+'</span></div>';}).join('')||'<div class="call">No players found on this roster.</div>';const core=ps.filter(p=>assetStatus(p)[0].includes('Core')).length,strong=ps.filter(p=>assetStatus(p)[0].includes('Strong')).length,review=ps.filter(p=>assetStatus(p)[0].includes('Review')).length;summary.innerHTML='<b>'+ps.length+' rostered players</b><br>'+core+' core assets • '+strong+' strong holds • '+review+' review candidates<br><br><span class="small">These are dynasty-value guardrails, not weekly start/sit scores. A future weekly engine will layer matchup, bye, injury and Vegas information on top without overwriting long-term roster value.</span>';status.textContent='Team loaded.';}catch(err){status.textContent='Could not load team: '+err.message;}}
 document.addEventListener('click',e=>{if(e.target&&e.target.id==='ftLoadRoster')loadMyTeam();});
 window.ftRefreshTeamChoices=refreshTeamChoices;
})();
</script>`;
  return text
    .replace("function save(){localStorage.setItem('ftAdaptiveV3',JSON.stringify(state))}","function save(){try{const slim={teams:state.teams,slot:state.slot,overall:state.overall,rounds:state.rounds,draftId:state.draftId,drafted:state.drafted,league:state.league};localStorage.setItem('ftAdaptiveV3',JSON.stringify(slim));}catch(e){console.warn('Save skipped',e)}}")
    .replace('60% Full Throttle + 40% dynasty startup market. Market rank is no longer Sleeper search order.','60% Full Throttle + 40% dynasty startup market.')
    .replace('<main class="wrap grid">','<main id="draftPane" class="wrap grid">')
    .replace('</head>',polish+'</head>')
    .replace('</header>','</header>'+sitebar+nav+ads)
    .replace('</main>','</main>'+manager)
    .replace('</body>',footer+appjs+'</body>');
}
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET')return;
  const u=new URL(event.request.url);
  if(u.origin===location.origin&&(u.pathname.endsWith('/')||u.pathname.endsWith('/index.html'))){
    event.respondWith(fetch(event.request,{cache:'no-store'}).then(async resp=>{
      const text=patchHtml(await resp.text());
      return new Response(text,{status:resp.status,statusText:resp.statusText,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}});
    }).catch(()=>caches.match('./index.html')));
    return;
  }
  event.respondWith(fetch(event.request).then(resp=>{const copy=resp.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));return resp;}).catch(()=>caches.match(event.request)));
});
