const CACHE='downmetric-v11';
const ASSETS=['./manifest.webmanifest','./icon-192.png','./icon-512.png'];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)));self.skipWaiting();});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))));self.clients.claim();});
function patchHtml(text){
  text=text.replaceAll('FULL THROTTLE','DOWNMETRIC').replaceAll('Full Throttle','DownMetric').replaceAll('FT #','DM #');
  text=text.replace('60% DownMetric + 40% dynasty startup market. Market rank is no longer Sleeper search order.','60% DownMetric + 40% dynasty startup market.');
  text=text.replace('Adaptive Scouting Formula','DownMetric Scouting Formula');
  text=text.replace('<title>DownMetric Draft Lab</title>','<title>DownMetric | Fantasy Football Intelligence</title>');
  const css=`<style id="dm-ui">.dmnav{max-width:1400px;margin:10px auto 0;padding:0 14px;display:flex;gap:7px;overflow-x:auto}.dmtab{width:auto;min-width:max-content;padding:9px 13px;min-height:38px;border:1px solid #31553b;background:#0a1d12;color:#d9e4da;border-radius:10px;text-transform:none;font-size:12px}.dmtab.active{background:#f2c94c;color:#172014}.dmpane{max-width:1400px;margin:14px auto;padding:0 14px}.dmpane.hidden{display:none}.dmcard{background:linear-gradient(145deg,#102719fa,#08170efa);border:1px solid #31553b;border-radius:14px;padding:15px}.dmgrid{display:grid;grid-template-columns:1.1fr .9fr;gap:14px}.dmroster{display:grid;gap:7px}.dmplayer{display:grid;grid-template-columns:1fr auto;gap:10px;padding:10px;border:1px solid #31553b;border-radius:10px;background:#07170e}.dmtag{font-size:10px;font-weight:800;color:#f2c94c}.dmbrand{max-width:1400px;margin:auto;padding:8px 14px 0;color:#a9b8aa;font-size:11px}.dmbrand b{color:#f2c94c}@media(max-width:900px){.dmgrid{grid-template-columns:1fr}}@media(max-width:650px){.dmnav{position:sticky;top:0;z-index:35;background:#06120bf5;padding-top:8px;padding-bottom:8px}.dmtab{font-size:11px;padding:8px 10px}}</style>`;
  const nav=`<div class="dmbrand"><b>DOWNMETRIC</b> • Fantasy Football Intelligence</div><nav class="dmnav"><button class="dmtab active" data-dm="draft">🏈 Draft Lab</button><button class="dmtab" data-dm="team">🏠 My Team</button><button class="dmtab" data-dm="lineup">📋 Lineup</button><button class="dmtab" data-dm="waivers">🔄 Waivers</button><button class="dmtab" data-dm="trades">🤝 Trades</button><button class="dmtab" data-dm="players">📈 Players</button></nav>`;
  const panes=`<section id="dmTeam" class="dmpane hidden"><div class="dmgrid"><div class="dmcard"><h2>🏠 My Team</h2><div class="call"><b>Roster-value protection:</b> a bye week or one-week matchup never makes a dynasty asset an automatic drop.</div><label>Select your Sleeper roster</label><select id="dmRoster"><option>Load your league in Draft Lab first</option></select><button id="dmLoad" style="margin-top:8px">Load My Team</button><div id="dmStatus" class="small" style="margin-top:8px"></div><div id="dmList" class="dmroster" style="margin-top:12px"></div></div><div class="dmcard"><h2>Roster Command</h2><div id="dmSummary" class="call">Load your roster to see dynasty-oriented hold guidance.</div></div></div></section><section id="dmLineup" class="dmpane hidden"><div class="dmcard"><h2>📋 Lineup Optimizer</h2><p class="small">Weekly start/sit recommendations with matchup, injuries, bye weeks, usage and Vegas signals are being built here.</p></div></section><section id="dmWaivers" class="dmpane hidden"><div class="dmcard"><h2>🔄 Waiver Assistant</h2><p class="small">This will compare free agents against the bottom of your roster and protect valuable players from bad one-week drops.</p></div></section><section id="dmTrades" class="dmpane hidden"><div class="dmcard"><h2>🤝 Trade Center</h2><p class="small">Dynasty value, lineup impact, roster construction and contender/rebuild context will live here.</p></div></section><section id="dmPlayers" class="dmpane hidden"><div class="dmcard"><h2>📈 Player Intelligence</h2><p class="small">Dynasty value, rest-of-season outlook, Vegas signal, historical profile and usage trends will live here.</p></div></section>`;
  const js=`<script id="dm-tabs">(()=>{const pane={draft:'draftPane',team:'dmTeam',lineup:'dmLineup',waivers:'dmWaivers',trades:'dmTrades',players:'dmPlayers'};function show(k){Object.entries(pane).forEach(([x,id])=>{const el=document.getElementById(id);if(el)el.classList.toggle('hidden',x!==k)});document.querySelectorAll('.dmtab').forEach(b=>b.classList.toggle('active',b.dataset.dm===k));if(k==='team')choices()}document.addEventListener('click',e=>{const t=e.target.closest('.dmtab');if(t)show(t.dataset.dm);if(e.target&&e.target.id==='dmLoad')loadTeam()});async function choices(){const id=document.getElementById('leagueId')?.value.trim(),sel=document.getElementById('dmRoster'),st=document.getElementById('dmStatus');if(!id||!sel)return;try{st.textContent='Reading league rosters…';const [rr,ur]=await Promise.all([fetch('https://api.sleeper.app/v1/league/'+id+'/rosters'),fetch('https://api.sleeper.app/v1/league/'+id+'/users')]);const rs=await rr.json(),us=await ur.json(),um=new Map(us.map(u=>[u.user_id,u]));window.dmRosters=rs;sel.innerHTML=rs.map(r=>'<option value="'+r.roster_id+'">'+(um.get(r.owner_id)?.metadata?.team_name||um.get(r.owner_id)?.display_name||'Roster '+r.roster_id)+'</option>').join('');st.textContent='Choose your team, then tap Load My Team.'}catch(e){st.textContent='Could not load rosters.'}}async function loadTeam(){const rid=+document.getElementById('dmRoster').value,st=document.getElementById('dmStatus'),list=document.getElementById('dmList'),sum=document.getElementById('dmSummary');try{const r=(window.dmRosters||[]).find(x=>+x.roster_id===rid);if(!r)throw Error();if(!state.players?.length){const pr=await fetch('https://api.sleeper.app/v1/players/nfl'),P=await pr.json();state.players=Object.values(P).filter(p=>p&&p.player_id&&['QB','RB','WR','TE'].includes(p.position))}const starters=new Set(r.starters||[]),taxi=new Set(r.taxi||[]),reserve=new Set(r.reserve||[]);const ps=(r.players||[]).map(id=>state.players.find(p=>p.player_id===id)).filter(Boolean);list.innerHTML=ps.map(p=>{let mr=999;try{mr=marketRank(p)}catch(e){};let tag=mr<=36?'🔒 Core Asset':mr<=100?'✅ Strong Hold':mr<=180?'🟡 Hold / Monitor':'🔎 Review';let spot=starters.has(p.player_id)?'Starter':taxi.has(p.player_id)?'Taxi':reserve.has(p.player_id)?'IR / Reserve':'Bench';return '<div class="dmplayer"><div><b>'+name(p)+'</b><div class="small">'+(p.team||'FA')+' • '+p.position+' • '+spot+'</div></div><span class="dmtag">'+tag+'</span></div>'}).join('');sum.innerHTML='<b>'+ps.length+' rostered players</b><br><span class="small">Weekly availability and dynasty value are tracked separately.</span>';st.textContent='Team loaded.'}catch(e){st.textContent='Could not load team.'}}})();</script>`;
  text=text.replace('<main class="wrap grid">','<main id="draftPane" class="wrap grid">');
  text=text.replace('</head>',css+'</head>').replace('</header>','</header>'+nav).replace('</main>','</main>'+panes).replace('</body>',js+'</body>');
  return text;
}
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const u=new URL(event.request.url);if(u.origin===location.origin&&(u.pathname.endsWith('/')||u.pathname.endsWith('/index.html'))){event.respondWith(fetch(event.request,{cache:'no-store'}).then(async r=>new Response(patchHtml(await r.text()),{status:r.status,statusText:r.statusText,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}})));return;}event.respondWith(fetch(event.request).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(event.request,copy));return r}).catch(()=>caches.match(event.request)));});